### ISSUE TITLE
Loading full species list generates socket exception

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/oznome-demo#2]
Too many open files. Stacktrace follows:
java.net.SocketException: Too many open files
        at java.net.Socket.createImpl(Socket.java:460)
        at java.net.Socket.connect(Socket.java:587)
        at com.mongodb.DBPort.ensureOpen(DBPort.java:255)
        at com.mongodb.DBPort.<init>(DBPort.java:89)
        at com.mongodb.DBPortFactory.create(DBPortFactory.java:28)
        at com.mongodb.PooledConnectionProvider$ConnectionItemFactory.create(PooledConnectionProvider.java:186)
        at com.mongodb.PooledConnectionProvider$ConnectionItemFactory.create(PooledConnectionProvider.java:183)
        at com.mongodb.ConcurrentPool.createNewAndReleasePermitIfFailure(ConcurrentPool.java:150)
        at com.mongodb.ConcurrentPool.get(ConcurrentPool.java:118)
        at com.mongodb.PooledConnectionProvider.get(PooledConnectionProvider.java:75)
        at com.mongodb.DefaultServer.getConnection(DefaultServer.java:61)
        at com.mongodb.BaseCluster$WrappedServer.getConnection(BaseCluster.java:248)
        at com.mongodb.DBTCPConnector$MyPort.getConnection(DBTCPConnector.java:503)
        at com.mongodb.DBTCPConnector$MyPort.get(DBTCPConnector.java:451)
        at com.mongodb.DBTCPConnector.getPrimaryPort(DBTCPConnector.java:409)
        at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:182)
        at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:165)
        at com.mongodb.DBCollection.insert(DBCollection.java:93)
        at com.mongodb.DBCollection.insert(DBCollection.java:78)
        at com.mongodb.DBCollection.insert(DBCollection.java:120)
        at com.gmongo.internal.Patcher._invoke(Patcher.groovy:49)
        at com.gmongo.internal.Patcher$__patchInternal_closure1.doCall(Patcher.groovy:38)
        at au.org.ala.regions.PatentService.fetch(PatentService.groovy:64)
        at au.org.ala.regions.PatentService$_fetchAll_closure1_closure3.doCall(PatentService.groovy:29)
        at groovyx.gpars.pa.GParsPoolUtilHelper$_eachParallelPA_closure8.doCall(GParsPoolUtilHelper.groovy:189)
        at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
        at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
        at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:118)
        at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
        at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
        at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
        at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
        at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
2015-06-03 09:27:05,782 ERROR [GrailsExceptionResolver] Unable to render errors view: Error initializing GroovyPageView
java.lang.RuntimeException: Error initializing GroovyPageView
        at com.nerderg.ajaxanywhere.AAFilter.doFilter(AAFilter.java:56)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: I/O error reading stream for resource [URL [file:/home/pal155/src/oznome-demo/grails-app/views/error.gsp]]: /home/pal155/src/oznome-demo/grails-app/views/error.gsp (Too many open files)
        ... 8 more
Caused by: java.io.FileNotFoundException: /home/pal155/src/oznome-demo/grails-app/views/error.gsp (Too many open files)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        ... 8 more
2015-06-03 09:27:05,802 ERROR [[grails]] Servlet.service() for servlet grails threw exception
java.io.FileNotFoundException: /home/pal155/src/oznome-demo/grails-app/views/error.gsp (Too many open files)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.nerderg.ajaxanywhere.AAFilter.doFilter(AAFilter.java:56)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2015-06-03 09:27:05,803 ERROR [[default]] Servlet.service() for servlet [default] in context with path [/oznome-demo] threw exception [Request processing failed; nested exception is org.codehaus.groovy.grails.exceptions.GrailsRuntimeException: java.lang.RuntimeException: Error initializing GroovyPageView] with root cause
java.io.FileNotFoundException: /home/pal155/src/oznome-demo/grails-app/views/error.gsp (Too many open files)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.nerderg.ajaxanywhere.AAFilter.doFilter(AAFilter.java:56)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by charvolant** [comment]
Fix in https://github.com/AtlasOfLivingAustralia/oznome-demo/pull/3
